# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: Merge

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git checkout -b cthulhu
      - run: |
          while read lc; do
            git branch $lc origin/$lc;
            git filter-repo --path .hgtags --path .hgignore --invert-paths --force --refs $lc;
            git filter-repo --to-subdirectory-filter $lc --force --refs $lc;
          done < firefox-locales
      - run: git merge --allow-unrelated-histories $(tr '\n' ' ' < firefox-locales)
      - run: git push origin cthulhu
