# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: Merge

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: sudo apt-get install -y git-filter-repo
      - run: git checkout -b cthulhu
      - run: |
          while read lc; do
            git branch $lc origin/$lc;
            git filter-repo --path .hgtags --path .hgignore --invert-paths --force --refs $lc;
            git filter-repo --to-subdirectory-filter $lc --force --refs $lc;
          done < firefox-locales
      - run: >
          git merge --no-edit --allow-unrelated-histories
          ace ach af ak an ar as ast az be bg bn bn-BD bn-IN bo br brx bs ca ca-valencia cak ckb crh
          cs csb cy da de dsb el en-CA en-GB en-ZA eo es-AR es-CL es-ES es-MX et eu fa ff fi fr frp
          fur fy-NL ga-IE gd gl gn gu-IN gv he hi-IN hr hsb hto hu hy-AM hye ia id ilo is it ixl ja
          ja-JP-mac ka kab kk km kn ko kok ks ku lb lg lij lo lt ltg lv mai meh mix mk ml mn mr ms
          my nb-NO ne-NP nl nn-NO nr nso ny oc or pa-IN pai pbb pl ppl pt-BR pt-PT quy qvi rm ro ru
          rw sah sat sc scn sco si sk skr sl son sq sr ss st sv-SE sw szl ta ta-LK te tg th tl tn tr
          trs ts tsz uk ur uz ve vi wo xcl xh zam zh-CN zh-TW zu
      - run: git push origin cthulhu
